### ISSUE TITLE
Crash when using registerMethods

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [trishume/ddbus#37] opened 2018-03-24 23:30 UTC
```d
import std.stdio;
import ddbus;

private MessageRouter router;

class Handler {
	public int test() {
		return 42;
	}
}

void main()
{
	//Establish connection to DBus.
	Connection conn = connectToBus();

	//Set up message router.
	router = new MessageRouter();

	//Setup handler
	Handler handler = new Handler();

	//Register methods
	registerMethods(router, "/", "dk.eclipsingr.nice", handler);

	//Register router and run loop.
	registerRouter(conn, router);
	bool gotem = requestName(conn, "dk.eclipsingr.nice");
	while (true) {
		conn.tick();
	}
}
```

When running this code, and trying to index the dbus router with d-feet the following exception occurs:
```
core.exception.AssertError@/usr/include/dmd/phobos/std/algorithm/iteration.d(3761): Attempting to fetch the front of an empty splitter.
----------------
??:? _d_assert_msg [0x47dee2]
/usr/include/dmd/phobos/std/algorithm/iteration.d:3761 pure @property @safe immutable(char)[] std.algorithm.iteration.splitter!("a == b", immutable(char)[], char).splitter(immutable(char)[], char).Result.front() [0x476291]
../../../.dub/packages/ddbus-2.3.0/ddbus/source/ddbus/router.d:184 pure @safe immutable(char)[] ddbus.router.MessageRouter.introspectXML(immutable(char)[]).__lambda6!(immutable(char)[]).__lambda6(immutable(char)[]) [0x471266]
/usr/include/dmd/phobos/std/algorithm/iteration.d:600 pure @property @safe immutable(char)[] std.algorithm.iteration.MapResult!(ddbus.router.MessageRouter.introspectXML(immutable(char)[]).__lambda6, std.algorithm.iteration.MapResult!(ddbus.router.MessageRouter.introspectXML(immutable(char)[]).__lambda5, std.algorithm.iteration.FilterResult!(ddbus.router.MessageRouter.introspectXML(immutable(char)[]).__lambda4,object.byKey!(ddbus.router.MessageHandler[ddbus.router.MessagePattern], ddbus.router.MessagePattern, ddbus.router.MessageHandler).byKey(ddbus.router.MessageHandler[ddbus.router.MessagePattern]).Result).FilterResult).MapResult).MapResult.front() [0x45e7bd]
/usr/include/dmd/phobos/std/array.d:134 pure @safe immutable(char)[][] std.array.array!(std.algorithm.iteration.MapResult!(ddbus.router.MessageRouter.introspectXML(immutable(char)[]).__lambda6, std.algorithm.iteration.MapResult!(ddbus.router.MessageRouter.introspectXML(immutable(char)[]).__lambda5, std.algorithm.iteration.FilterResult!(ddbus.router.MessageRouter.introspectXML(immutable(char)[]).__lambda4, object.byKey!(ddbus.router.MessageHandler[ddbus.router.MessagePattern], ddbus.router.MessagePattern, ddbus.router.MessageHandler).byKey(ddbus.router.MessageHandler[ddbus.router.MessagePattern]).Result).FilterResult).MapResult).MapResult).array(std.algorithm.iteration.MapResult!(ddbus.router.MessageRouter.introspectXML(immutable(char)[]).__lambda6, std.algorithm.iteration.MapResult!(ddbus.router.MessageRouter.introspectXML(immutable(char)[]).__lambda5, std.algorithm.iteration.FilterResult!(ddbus.router.MessageRouter.introspectXML(immutable(char)[]).__lambda4, object.byKey!(ddbus.router.MessageHandler[ddbus.router.MessagePattern], ddbus.router.MessagePattern, ddbus.router.MessageHandler).byKey(ddbus.router.MessageHandler[ddbus.router.MessagePattern]).Result).FilterResult).MapResult).MapResult) [0x466cf5]
../../../.dub/packages/ddbus-2.3.0/ddbus/source/ddbus/router.d:182 immutable(char)[] ddbus.router.MessageRouter.introspectXML(immutable(char)[]) [0x45b1d3]
../../../.dub/packages/ddbus-2.3.0/ddbus/source/ddbus/router.d:197 void ddbus.router.MessageRouter.handleIntrospect(immutable(char)[], ddbus.thin.Message, ddbus.thin.Connection) [0x45b327]
../../../.dub/packages/ddbus-2.3.0/ddbus/source/ddbus/router.d:79 bool ddbus.router.MessageRouter.handle(ddbus.thin.Message, ddbus.thin.Connection) [0x45a9dd]
../../../.dub/packages/ddbus-2.3.0/ddbus/source/ddbus/router.d:209 filterFunc [0x470b74]
??:? dbus_connection_dispatch [0xf3e8dd34]
Program exited with code 1
```

It only happens when using registerMethods

**Comment by WebFreak001** [comment] 2018-03-25 09:05
can't reproduce, works fine on my machine. It looks much more like some program is trying to introspect your app and there is an issue with the introspection xml generation, could you state what else you are using to access this?

**Comment by WebFreak001** [comment] 2018-03-25 09:21
actually when checking using a dbus introspection tool I can reproduce it. I don't think it's valid to bind to `/`, rather you should bind to `/org/domain/Classname` and attach `org.domain.Interface1` `org.domain.Interface2` `org.domain.Interface3` etc. to it.

However I can push a fix for this real quick.

**Comment by WebFreak001** [comment] 2018-03-25 09:52
can you try setting the ddbus version to `~master` to see if the issue is gone? It should work now

**Closed as completed** 2018-08-17 16:43 UTC
